### ISSUE TITLE
which formats ?

### ISSUE THREAD

**Issue by BogusCurry** [Misterblue/convoar#1]
Hello there ;D
You write "Command line application for converting OpenSimulator OAR files into various other formats."

Now my question, in which formats mean you ?

Greetings
Bogus

**Comment by Misterblue** [comment]
It has been nearly a year since you asked the question. Since I haven't stopped working on convoar, I will start keeping track of what's going on here.

I had tried using assimp (http://www.assimp.org/) to convert the meshes into most any format (OBJ, DAE, ...) but, after several months playing at getting the C++ to C# interface to work, I finally give up and am only outputting GLTF. The plan is to do an OAR to GLTF conversion and then collect a tool chain that can input that GLTF and optimize it.

I will have a convoar release real soon now that does the basic conversion.
